### ISSUE TITLE
Oracle database connection regression in 1.43.0

### ISSUE THREAD

**Issue by lmocsi** [pola-rs/polars#28463]
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
# 1.42.1 ok
# 1.43.0 error

import polars as pl
import oracledb
from my_config import user, pw, dsn, host, port

with oracledb.connect(user=user, password=pw, dsn=f"{host}:{port}/{dsn}") as con:
    v_sql = 'select 1 as a from dual'
    with con.cursor() as cur:
        df = pl.read_database(query=v_sql, connection=cur)

```

### Log output

```shell
File "xxx", line 18, in <module>
    df = pl.read_database(query=v_sql, connection=cur)
  File "C:\Users\xxx\AppData\Roaming\Python\Python313\site-packages\polars\io\database\functions.py", line 287, in read_database
    ).to_polars(
      ~~~~~~~~~^
        batch_size=batch_size,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        infer_schema_length=infer_schema_length,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\xxx\AppData\Roaming\Python\Python313\site-packages\polars\io\database\_executor.py", line 603, in to_polars
    frame = frame_init(
        batch_size=batch_size,
    ...<2 lines>...
        infer_schema_length=infer_schema_length,
    )
  File "C:\Users\xxx\AppData\Roaming\Python\Python313\site-packages\polars\io\database\_executor.py", line 254, in _from_arrow
    return frames if iter_batches else next(frames)  # type: ignore[arg-type,return-value]
                                       ~~~~^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python313\site-packages\polars\io\database\_executor.py", line 248, in <genexpr>
    for batch in self._fetch_arrow(
                 ~~~~~~~~~~~~~~~~~^
        driver_properties,
        ^^^^^^^^^^^^^^^^^^
        iter_batches=iter_batches,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
        batch_size=batch_size,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\xxx\AppData\Roaming\Python\Python313\site-packages\polars\io\database\_executor.py", line 165, in _fetch_arrow
    yield getattr(self.result, fetch_method)()
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Cursor' object has no attribute 'fetch_df_all'
```

### Issue description

Any (simple) Oracle database query fails with `'Cursor' object has no attribute 'fetch_df_all'` error on polars==1.43.0
Works fine on polars==1.42.1

### Expected behavior

Run without error.

### Installed versions

<details>

```
--------Version info---------
Polars:              1.43.0
Index type:          UInt32
Platform:            Windows-11-10.0.22631-SP0
Python:              3.13.13 (tags/v3.13.13:01104ce, Apr  7 2026, 19:25:48) [MSC v.1944 64 bit (AMD64)]
Runtime:             rt32

----Optional dependencies----
Azure CLI            'az' is not recognized as an internal or external command,
operable program or batch file.
<not installed>
adbc_driver_manager  <not installed>
altair               <not installed>
azure.identity       <not installed>
boto3                <not installed>
cloudpickle          <not installed>
connectorx           0.4.5
deltalake            <not installed>
fastexcel            0.19.0
fsspec               <not installed>
gevent               <not installed>
google.auth          <not installed>
great_tables         <not installed>
matplotlib           3.10.8
numpy                2.4.2
openpyxl             <not installed>
pandas               3.0.0
polars_cloud         <not installed>
pyarrow              <not installed>
pydantic             <not installed>
pyiceberg            <not installed>
sqlalchemy           <not installed>
torch                <not installed>
xlsx2csv             <not installed>
xlsxwriter           <not installed>
```

</details>

**Comment by alexander-beedie** [comment]
Which oracle driver lib/version are you using? 🤔 (This fast-path should be gated by `oracledb >= 3.0`, where `fetch_df_all` was [added](https://python-oracledb.readthedocs.io/en/latest/release_notes.html#id31); possibly the check isn't working properly, or the version needs adjusting).

**Comment by lmocsi** [comment]
oracledb 4.0.2

**Comment by Jhsmit** [comment]
I'm experiencing a similar issue when using sqlalchemy
works on polars 1.42.1

```python
import polars as pl
from sqlalchemy import create_engine, literal_column, select

url = "oracle+oracledb://user:password@host:port/XXX"
engine = create_engine(url)

# WORKS
with engine.connect() as conn:
    print(pl.read_database("SELECT 1 AS one FROM DUAL", connection=conn))

#  FAILS
stmt = select(literal_column("1").label("one"))
with engine.connect() as conn:
    print(pl.read_database(stmt, connection=conn))
```

traceback
```
  File "/home/.../lib/python3.13/site-packages/oracledb/cursor.py", line 852, in execute
    self._prepare_for_execute(statement, parameters, keyword_parameters)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../lib/python3.13/site-packages/oracledb/cursor.py", line 159, in _prepare_for_execute
    self._normalize_statement(statement),
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/.../lib/python3.13/site-packages/oracledb/cursor.py", line 137, in _normalize_statement
    statement = statement.strip()
                ^^^^^^^^^^^^^^^
AttributeError: 'Select' object has no attribute 'strip'
```

polars:     1.43.2
oracledb:   4.0.2
sqlalchemy: 2.0.46

**Comment by lmocsi** [comment]
Can this bug be fixed by polars 2.0?

**Comment by kahemker** [comment]
I don't have any help on how to fix this.  This particular regression bit me today when I was trying out the latest version.  I spent some AI tokens to try to learn more and this is the best I got.  Maybe someone who knows more than me can propose a solution.  Below is AI generated.  Please let me know if there's anything else I can do to help.

I can confirm this regression and narrow its introduction to **Polars 1.43.0**.

I tested the complete stable release interval from 1.42.1 through 1.43.2:

| Polars | Result |
|---|---|
| 1.42.1 | Passes consistently |
| 1.43.0 | Fails consistently |
| 1.43.1 | Fails consistently |
| 1.43.2 | Fails consistently |

Each version was tested five times in a separate environment while holding the other components constant:

- Python 3.12.10
- python-oracledb 3.1.1
- SQLAlchemy 2.0.41
- Windows 10

Polars 1.43.0 and 1.43.1, and their corresponding `polars-runtime-32` releases, are currently yanked on PyPI. I explicitly pinned both distributions for forensic testing. All five runs of each version produced the same failure; no flaky results were observed.

Before every Polars test, a direct SQLAlchemy `SELECT 1 FROM DUAL` control passed. This rules out authentication, connectivity, and general SQLAlchemy execution failures.

## SQLAlchemy `Select` failure

This fails beginning with Polars 1.43.0:

```python
import polars as pl
from sqlalchemy import literal, select

stmt = select(literal(1).label("VALUE"))
df = pl.read_database(stmt, engine)
```

The relevant error with python-oracledb 3.1.1 is:

```
TypeError: Argument 'statement' has incorrect type (expected str, got Select)
```

The traceback shows the SQLAlchemy `Select` reaching:

```python
[oracledb.Connection](http://oracledb.connection/).fetch_df_all(...)
[cursor.execute](http://cursor.execute/)(statement, parameters)
```

without first being compiled by SQLAlchemy.

## SQL-string behavior

I also tested a literal SQL string through the same SQLAlchemy engine:

```python
df = pl.read_database(
    "SELECT 1 AS VALUE FROM DUAL",
    engine,
)
```

This passes with Polars 1.42.1, but fails with 1.43.0, 1.43.1, and 1.43.2 in my python-oracledb 3.1.1 environment.

For 1.43.0/1.43.1, the error is:

```
TypeError: expected PyArrow Table, Array, or one or more RecordBatches;
got 'oracledb.interchange.dataframe.OracleDataFrame'
```

For 1.43.2, the equivalent error is:

```
TypeError: DataFrame constructor called with unsupported type
'OracleDataFrame' for the `data` parameter
```

This differs from the report above where a SQL string works with python-oracledb 4.0.2, so that part may also depend on the python-oracledb version. The SQLAlchemy `Select` failure appears reproducible with both python-oracledb 3.1.1 and 4.0.2.

## Apparent implementation boundary

Comparing the installed Polars packages shows that 1.43.0 introduces `OracleCursorProxy`. The database executor detects an Oracle SQLAlchemy engine, unwraps its raw python-oracledb connection, and routes the read through `fetch_df_all`/`fetch_df_batches`.

The proxy stores the supplied query unchanged:

```python
def execute(self, query, **execute_options):
    [self.query](http://self.query/) = query
    return self

def fetch_df_all(self):
    return [self.connection](http://self.connection/).fetch_df_all(
        [self.query](http://self.query/),
        **self.execute_options,
    )
```

This Oracle proxy/path is absent in Polars 1.42.1.

It appears that this new fast path causes at least two issues:

1. SQLAlchemy statement objects bypass SQLAlchemy compilation and are passed directly to python-oracledb, which expects a SQL string.
2. With python-oracledb 3.1.1, the returned `OracleDataFrame` is not accepted by the selected Polars conversion path.

## Summary

- **Last known good:** Polars 1.42.1
- **First release containing the regression:** Polars 1.43.0
- **First normally installable bad release after the yanked releases:** Polars 1.43.2

A possible fix may be to preserve the normal SQLAlchemy execution path whenever the query is a SQLAlchemy executable object, rather than unwrapping the raw Oracle connection. The Oracle fast path may also need capability/conversion checks for both the supplied connection object and the dataframe object returned by `fetch_df_all`.

**Comment by lmocsi** [comment]
@alexander-beedie This is not fixed in polars 2.0.0rc1. Is this normal? Which version will it be fixed?

**Comment by alexander-beedie** [comment]
> [@alexander-beedie](https://github.com/alexander-beedie) This is not fixed in polars 2.0.0rc1. Is this normal? Which version will it be fixed?

@lmocsi: Looks like it got caught in a merge/branching history issue during the preparation for cutting over to the upcoming 2.0; we're landing the same PR again, here: https://github.com/pola-rs/polars/pull/29142 ;)
