### ISSUE TITLE
getting AttributeError when using `.is_in` on polars 0.9.7, but works on polars 0.8.*

### ISSUE THREAD

**Issue by chenrocky** [pola-rs/polars#1382]
#### Are you using Python or Rust?

**Python**.

#### Which feature gates did you use?

This can be ignored by Python users.

#### What version of polars are you using?

0.9.7

#### What operating system are you using polars on?

rhel8

#### Describe your bug.

getting AttributeError when using `.is_in` on polars 0.9.7, but works on polars 0.8.*

#### What are the steps to reproduce the behavior?

```
import polars as pl

from polars import col

# example data
d = {
    'col1': ["a", "a", "a", "a", "a", "b", "b", "b", "b", "b", "c", "c", "c", "c","c"],
    'col2': [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
    'col3': [1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1]
}

df_pl = pl.DataFrame(data=d)

df_pl.filter(
    (col("col2").is_in([0, 4]))
)
```

#### What is the actual behavior?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-bdbd6785e43e> in <module>
     13 
     14 df_pl.filter(
---> 15     (col("col2").is_in([0, 4]))
     16 )

/opt/app-root/lib64/python3.8/site-packages/polars/lazy/expr.py in is_in(self, other)
   1108         """
   1109         other = expr_to_lit_or_expr(other, str_to_lit=False)
-> 1110         return wrap_expr(self._pyexpr.is_in(other._pyexpr))
   1111 
   1112     def repeat_by(self, by: "Expr") -> "Expr":

AttributeError: 'list' object has no attribute '_pyexpr'
```

#### What is the expected behavior?

I expected for this code to return a df with rows that only have a value of 0 or 4 in `col2`

**Comment by potter420** [comment]
Hi, `is_in` is replaced by `isin` and you have to convert lists to Series, so the above can be:
```
df_pl.filter(
    (col("col2").isin(pl.Series([0, 4])))
)
```

**Comment by chenrocky** [comment]
> Hi, `is_in` is replaced by `isin` and you have to convert lists to Series, so the above can be:
> 
> ```
> df_pl.filter(
>     (col("col2").isin(pl.Series([0, 4])))
> )
> ```

Running that code throws this error for me:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-5a9feb9595c1> in <module>
     15 
     16 df_pl.filter(
---> 17     (col("col2").isin(pl.Series([0, 4])))
     18 )

AttributeError: 'Expr' object has no attribute 'isin'
```

**Comment by potter420** [comment]
@chenrocky sorry, it is still `is_in`, but the series part stay
```
df_pl.filter(
    (col("col2").is_in(pl.Series([0, 4])))
)

```

**Comment by ritchie46** [comment]
@potter420's answer is correct, a `Series` is expected.

However to improve ergonomics, I added (and tested) the list functionality as well: #1384

**Comment by ritchie46** [comment]
Added and released
