### ISSUE TITLE
Readme says >=1.80, but polars-streaming requires >=1.88

### ISSUE THREAD

**Issue by markkimsal** [pola-rs/polars#24294]
### Description

Project README claims rust >=1.80 is required, but "getting started" cannot compile on rust 1.87

```
error[E0658]: `let` expressions in this position are unstable
   --> cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-stream-0.50.0/src/nodes/io_sources/multi_file_reader/extra_ops/column_selector.rs:645:26
    |
645 |                       ) && let Some(extra_col) =
    |  __________________________^
646 | |                         incoming_fields
647 | |                             .iter()
648 | |                             .find_map(|(physical_id, iceberg_column)| {
649 | |                                 (!target_fields.contains_key(physical_id)).then_some(iceberg_column)
650 | |                             })
    | |______________________________^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
```

Sample Cargo.toml
```toml
[package]
name = "polars-example"
version = "0.1.0"
edition = "2024"

[dependencies]
polars = { version = "=0.50.0", features = ["lazy"] }
```

Please add `rust-version="1.88"` to polars-stream Cargo.toml

https://docs.pola.rs/user-guide/getting-started/#reading-writing 

### Link

https://docs.pola.rs/user-guide/getting-started/#reading-writing

**Comment by orlp** [comment]
We should update the number listed in the readme but I don't think we're anywhere near careful enough to start setting `rust-version` in `Cargo.toml`, it so easily goes out of date.

**Comment by ritchie46** [comment]
I just think we should move away from mentioning the minimal version and just update to latest as we are always on a nightly no more than a few weeks old.
