### PR TITLE
fix(rust): Declare MSRV 1.95 in workspace.package

### LINKED ISSUE #24792: Polars Rust crate does not declare a Minimum Supported Rust Version but cannot compile with anything less than 1.88
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```console
> cargo add polars
<use Polars somewhere in project>

> cargo +1.87 build
error[E0658]: `let` expressions in this position are unstable
   --> /Users/<user>/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-utils-0.51.0/src/plpath.rs:306:12
    |
306 |         if let Some(scheme) = self.scheme()
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

   Compiling bson v2.15.0
For more information about this error, try `rustc --explain E0658`.
error: could not compile `polars-utils` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

> cargo +1.88 build
<succeeds>
```

### Log output

```shell

```

### Issue description

The [Polars crate](https://crates.io/crates/polars) does not declare a Minimum Supported Rust Version (MSRV):

Image

----

However, projects with Polars cannot be built with any Rust version less than `1.88`. This is because, at a minimum, Polars uses `if`-`let` chaining, [which was stabilized in `1.88`](https://blog.rust-lang.org/2025/06/26/Rust-1.88.0/). Here is the use reported by `cargo`:

https://github.com/pola-rs/polars/blob/faab1f8eeeb1ad1a60fbd6e433bfbc3239737422/crates/polars-utils/src/plpath.rs#L346-L356

### Expected behavior

1. Polars should explicitly set a Minimum Supported Rust Version (MSRV) so that `cargo` tooling can know about it.
    * This issue was very unexpected, and luckily I am able to upgrade from `1.85.1` to `1.89`. However, it isn't always possible in our corporate environment to upgrade out of sync with other Rust projects.
3. If the only thing preventing Polars from supporting earlier versions is `if`-`let` chains, then in my opinion, their use should be removed. The above code is very minimally improved by using an `if`-`let` chain.

### Installed versions

<details>

```toml
polars = { version = "0.51.0", optional = true, features = [
    "json",
    "lazy",
    "serde",
    "timezones",
] }
```

</details>

### PR DESCRIPTION
**Pull request by srivtx**
Closes #24792.

Polars needs Rust 1.95+ to build (let-chains in plpath.rs stabilised in 1.88, std::hint::cold_path stabilised in 1.95), but the workspace never advertised an MSRV. Users on older toolchains were hitting cryptic E0658 errors about unstable features instead of getting a clean cargo error.

This adds `rust-version = "1.95"` to `[workspace.package]` and inherits it on the two published crates users actually depend on (`polars` and `polars-python`). After this, `cargo +1.94 build` against a project that uses polars will fail fast with a readable message pointing at the required toolchain.

Verified locally with `cargo metadata --no-deps --format-version 1` — both `polars` and `polars-python` now report `rust_version: "1.95"` where they previously reported null.

This is a config-only change, no source code touched, so the existing test suite should be unaffected.

### CODE REVIEW

**Comment by srivtx** [comment]
Closing — the maintainers stated in #24792 that they don't want a declared MSRV and prefer to track the latest toolchain via rust-toolchain.toml. Doesn't make sense to push this against stated policy.
