### ISSUE TITLE
Does not compile with rustc 1.98.0-nightly

### ISSUE THREAD

**Issue by Chris00** [pola-rs/polars#27863]
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

When adding `polars-core` as a (dev) dependency, the compilation fails with
```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> /home/trch/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethnum-1.5.2/src/error.rs:16:14
   |
16 |     unsafe { mem::transmute(()) }
   |              ^^^^^^^^^^^^^^
   |
   = note: source type: `()` (0 bits)
   = note: target type: `TryFromIntError` (8 bits)

For more information about this error, try `rustc --explain E0512`.
error: could not compile `ethnum` (lib) due to 1 previous error
```

### Log output

```shell

```

### Issue description

See above.

### Expected behavior

The compilation should succeed. ;-)

### Installed versions

<details>

polars-core = { version = "0.54.3", features = ["fmt"] }

</details>

**Comment by cmdlineluser** [comment]
It seems to be an issue with ethnum 1.5.2 https://github.com/nlordell/ethnum-rs/pull/58 
https://github.com/pola-rs/polars/blob/d54df64dba1734ec4075151d221c5d797f8a0bf7/Cargo.lock#L1477-L1478

It does compile for me with 1.5.3

**Comment by MCharming98** [comment]
The 'ethnum' dependency version 1.5.2 contains an unsound transmute from '()' to 'TryFromIntError' that is rejected by recent Rust nightly compilers; upgrading to 'ethnum' 1.5.3 or later resolves this issue.

Consider:
- Update the Polars workspace to use 'ethnum' 1.5.3 by running 'cargo update -p ethnum'.
- Optionally update 'Cargo.toml' workspace dependencies to require 'ethnum = "1.5.3"'.

**Comment by orlp** [comment]
Note that in general we recommend sticking to the version found in `rust-toolchain.toml`. We don't guarantee we compile in any nightly version other than that (we do compile in stable).

**Comment by orlp** [comment]
Upgrading our toolchain is blocked on https://github.com/rust-lang/rust/issues/157420.

**Comment by orlp** [comment]
I've at least bumped our dependency on `ethnum` so this issue should no longer occur.

**Comment by cmdlineluser** [comment]
<strike>

@orlp `ethnum` seems to be back at 1.5.2

https://github.com/pola-rs/polars/blob/0d5e33fa3b99442f3ce9375ea6da624fc5c9fa4e/Cargo.lock#L1477-L1478

Not sure if it was an intended change, but just thought I'd flag it as I had to switch back to `nightly-2026-04-01` again.

</strike>

**Update:** Resolved by https://github.com/pola-rs/polars/pull/27964
