### ISSUE TITLE
ERROR: cannot find function `find` in module `strings`

### ISSUE THREAD

**Issue by leedstyh** [pola-rs/polars#14121]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
fn testcsv() -> Result<(), Box<dyn Error>> {
    let q = LazyCsvReader::new("000338.csv")
        .has_header(true)
        .finish()?
        .select([col("datetime").str().to_datetime(
            Some(TimeUnit::Microseconds),
            None,
            StrptimeOptions::default(),
            lit("raise"),
        )])
        .collect()?;

    dbg!(q);

    Ok(())
}
```

### Log output

```shell
Compiling polars-plan v0.37.0
error[E0425]: cannot find function `find` in module `strings`
   --> D:\App\Rust\cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-plan-0.37.0\src\dsl\function_expr\strings.rs:292:64
    |
292 |             Find { literal, strict } => map_as_slice!(strings::find, literal, strict),
    |                                                                ^^^^ not found in `strings`
    |
note: found an item that was configured out
   --> D:\App\Rust\cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-plan-0.37.0\src\dsl\function_expr\strings.rs:433:15
    |
433 | pub(super) fn find(s: &[Series], literal: bool, strict: bool) -> PolarsResult<Series> {
    |               ^^^^
    = note: the item is gated behind the `regex` feature

For more information about this error, try `rustc --explain E0425`.
error: could not compile `polars-plan` (lib) due to previous error
```

### Issue description

Building rust code with feature "strings" prints error, when on polars version 0.37.0.

Building works while back to polars version 0.36.2

### Expected behavior

Building should work on version 0.37.0

### Installed versions

<details>

polars = { version = "0.37.0", features = ["lazy", "strings"] }

</details>

**Comment by leedstyh** [comment]
Thanks @reswqa , and feel free to close this.

**Comment by humphreylee** [comment]
Hi, I have updated to latest version (0.37) and still encounter this problem. Will there be a release version incorporating the implemented fixes?

**Comment by coolstudio1678** [comment]
version 0.38.2  still encounter this problem

**Comment by coolstudio1678** [comment]
thanks，I update chrono to the latest version , the error disappeared.
