### ISSUE TITLE
How to get the last value of a series in 44.2 ?

### ISSUE THREAD

**Issue by weixingsun** [pola-rs/polars#20074]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
v43.1:  ma["column1"].iter().last().unwrap()
good
```

### Log output

```shell
v44.2 failed to compile : 
error[E0599]: no method named `iter` found for enum `polars::prelude::Column` in the current scope
            let last_value = &df["column1"].iter().last().unwrap();
                                            ^^^^
```

### Issue description

compile failed

### Expected behavior

compile success

### Installed versions

<details>
v44.2
</details>

**Comment by coastalwhite** [comment]
Column does not have an iter method. If you want to refer to the old Series method, use `Column::as_materialized_series()`. But you should be using .get(len-1) instead. `iter().last()` is extremely inefficient.

**Comment by weixingsun** [comment]
thanks, it works with latest 44.2
