### ISSUE TITLE
Rust library does not compile with `lazy` and `csv` features enabled.

### ISSUE THREAD

**Issue by LegoWolf** [pola-rs/polars#26735]
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

The simplest way to reproduce the problem is by running a cargo check within the Polars project using any version at 8edef11ffa3c1dbc0c1d46d01f1cdecd6f1eb797 or later:

```bash
cargo check -p polars --features=lazy,csv
```

### Log output

```shell
The output includes many warnings that are probably harmless, but also these errors that cause compilation to fail:


error[E0433]: cannot find `ndjson` in `super`
  --> crates/polars-stream/src/nodes/io_sources/csv/mod.rs:29:12
   |
29 | use super::ndjson::chunk_data_fetch::ChunkDataFetcher;
   |            ^^^^^^ could not find `ndjson` in `super`
   |
note: found an item that was configured out
  --> crates/polars-stream/src/nodes/io_sources/mod.rs:11:9
   |
10 | #[cfg(any(feature = "json", feature = "scan_lines"))]
   |          ------------------------------------------ the item is gated here
11 | pub mod ndjson;
   |         ^^^^^^

error[E0433]: cannot find type `RelaxedCell` in this scope
   --> crates/polars-stream/src/physical_plan/lower_ir.rs:671:45
    |
671 | ...                   prefetch_limit: RelaxedCell::new_usize(0),
    |                                       ^^^^^^^^^^^ use of undeclared type `RelaxedCell`
    |
help: consider importing this struct
    |
  1 + use polars_utils::relaxed_cell::RelaxedCell;
    |
```

### Issue description

This problem cropped up in my Rust project because I include the polars library with these features enabled. I can work around the problem by also including `json` and `parquet`, but it should probably not be necessary to include this overhead.

The problem was introduced in commit 8edef11ffa3c1dbc0c1d46d01f1cdecd6f1eb797.

### Expected behavior

The library should be able to compile with just `lazy` and `csv` enabled.

### Installed versions

Rust Toolchain: `nightly-2026-02-19` (as specified in polars file `rust-toolchain.toml`)

Feature gates:
<details>
`lazy`
`csv`
</details>
