### PR TITLE
fix(rust): add missing conditional compile flag for `StringFunction::Find`

### LINKED ISSUE #14121: ERROR: cannot find function `find` in module `strings`
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust
fn testcsv() -> Result<(), Box<dyn Error>> {
    let q = LazyCsvReader::new("000338.csv")
        .has_header(true)
        .finish()?
        .select([col("datetime").str().to_datetime(
            Some(TimeUnit::Microseconds),
            None,
            StrptimeOptions::default(),
            lit("raise"),
        )])
        .collect()?;

    dbg!(q);

    Ok(())
}
```

### Log output

```shell
Compiling polars-plan v0.37.0
error[E0425]: cannot find function `find` in module `strings`
   --> D:\App\Rust\cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-plan-0.37.0\src\dsl\function_expr\strings.rs:292:64
    |
292 |             Find { literal, strict } => map_as_slice!(strings::find, literal, strict),
    |                                                                ^^^^ not found in `strings`
    |
note: found an item that was configured out
   --> D:\App\Rust\cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-plan-0.37.0\src\dsl\function_expr\strings.rs:433:15
    |
433 | pub(super) fn find(s: &[Series], literal: bool, strict: bool) -> PolarsResult<Series> {
    |               ^^^^
    = note: the item is gated behind the `regex` feature

For more information about this error, try `rustc --explain E0425`.
error: could not compile `polars-plan` (lib) due to previous error
```

### Issue description

Building rust code with feature "strings" prints error, when on polars version 0.37.0.

Building works while back to polars version 0.36.2

### Expected behavior

Building should work on version 0.37.0

### Installed versions

<details>

polars = { version = "0.37.0", features = ["lazy", "strings"] }

</details>

### PR DESCRIPTION
**Pull request by reswqa**
It seems that we forget to add this flag when introduce `str.find`(No blame). I'm just curious if it's possible to get this error exposed early in the CI phase. 🤔 

This fixes #14121.

### CODE REVIEW

**Comment by ritchie46** [comment]
>  I'm just curious if it's possible to get this error exposed early in the CI phase. 🤔

We run cargo hack. Which is somewhat of an effort. There is just a combinatorial explosion of features.

**Review by ritchie46 — APPROVED** [review]
