### ISSUE TITLE
Compile failed after upgrade to 0.24

### ISSUE THREAD

**Issue by attila-lin** [pola-rs/polars#4900]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of polars.

### Issue Description

After upgrade to 0.24.0, compile failed.

```
error[E0599]: no method named `lst_concat` found for reference `&polars_core::chunked_array::ChunkedArray<ListType>` in the 
current scope
--> C:\Users\xxxxxxx\.cargo\registry\src\github.com-1ecc6299db9ec823\polars-lazy-0.24.0\src\dsl\function_expr\list.rs:40:14
   |
40 |     first_ca.lst_concat(other).map(|ca| ca.into_series())
   |              ^^^^^^^^^^ method not found in `&polars_core::chunked_array::ChunkedArray<ListType>`
```

### Reproducible Example

just upgrade

### Expected Behavior

compile success

### Installed Versions

<details>
Replace this line with a list of feature gates
</details>
polars = { version = "0.24.0", features = ["lazy", "parquet", "is_in", "dtype-categorical", "simd", "performant"] }

rustc -V
rustc 1.65.0-nightly (cf9ed0dd5 2022-09-15)

**Comment by ghuls** [comment]
You are very likely missing some features (`"list"`?). You can check `py-polars/Cargo.toml` to see which features are enabled in the Python version, to find the ones you need.

**Comment by attila-lin** [comment]
> You are very likely missing some features (`"list"`?). You can check `py-polars/Cargo.toml` to see which features are enabled in the Python version, to find the ones you need.

It works! Seems a breaking change.

Thx

**Comment by houyingkun** [comment]
> You are very likely missing some features (`"list"`?). You can check `py-polars/Cargo.toml` to see which features are enabled in the Python version, to find the ones you need.

Hello, I am a beginner in rust. I would like to ask, how do you know that the `"list"` feature is missing in this case?
