### ISSUE TITLE
Rust 0.41.1: error[E0412]: cannot find type `CloudOptions` in this scope

### ISSUE THREAD

**Issue by huxi** [pola-rs/polars#17156]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

I get the following compile error after upgrading from 0.40.x to 0.41.1 on both Rust 1.81.0-nightly and Rust 1.79.0:

```
   Compiling polars-plan v0.41.1
error[E0412]: cannot find type `CloudOptions` in this scope
   --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.41.1/src/plans/builder_dsl.rs:162:31
    |
162 |         cloud_options: Option<CloudOptions>,
    |                               ^^^^^^^^^^^^
    |
   ::: ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-plan-0.41.1/src/dsl/options.rs:43:1
    |
43  | pub struct JoinOptions {
    | ---------------------- similarly named struct `JoinOptions` defined here
    |
help: a struct with a similar name exists
    |
162 |         cloud_options: Option<JoinOptions>,
    |                               ~~~~~~~~~~~
help: consider importing this struct
    |
1   + use polars_io::cloud::CloudOptions;
    |
```

### Issue description

Compile error inside of polars itself.

### Expected behavior

polars itself should be able to compile.

### Installed versions

<details>

polars = { version = "0.41", default-features = false, features = ["csv", "fmt", "lazy", "regex", "strings", "temporal"] }

</details>

**Comment by ritchie46** [comment]
I believe we fixed this on main. What is the cargo.toml to reproduce this?

**Comment by huxi** [comment]
I put the info into the details.

This is the dependency definition:
`polars = { version = "0.41", default-features = false, features = ["csv", "fmt", "lazy", "regex", "strings", "temporal"] }`

Nothing special in there beside that.

**Comment by sportfloh** [comment]
In my case only this Cargo.toml entry is reproducing the compile error:
```
polars = { version = "0.41", features = ["lazy"] }
```

**Comment by ritchie46** [comment]
Can confirm that it is fixed on main. Patch coming up.
