### ISSUE TITLE
Linux compile error on tag 0.51

### ISSUE THREAD

**Issue by weixingsun** [pola-rs/polars#24600]
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

rust 1.88 on Linux 6.1
when upgrading rust polars from 0.50 to 0.51 , recompile app failed 

```rust
/home/test/.cargo/bin/rustc --version
rustc 1.88.0 (6b00bc388 2025-06-23)

```

### Log output

```shell
/home/test/.cargo/bin/cargo build --release
...
compile Compiling polars-stream v0.51.0
error[E0412]: cannot find type `AbortOnDropHandle` in module `tokio_util::task`
  --> /home/sun/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-stream-0.51.0/src/nodes/io_sinks/csv.rs:33:39
   |
33 |     io_task: Option<tokio_util::task::AbortOnDropHandle<PolarsResult<()>>>,
   |                                       ^^^^^^^^^^^^^^^^^ not found in `tokio_util::task`
   |
help: consider importing one of these structs
   |
1  + use crate::nodes::io_sinks::AbortOnDropHandle;
   |
1  + use crate::utils::task_handles_ext::AbortOnDropHandle;
   |
help: if you import `AbortOnDropHandle`, refer to it directly
   |
33 -     io_task: Option<tokio_util::task::AbortOnDropHandle<PolarsResult<()>>>,
33 +     io_task: Option<AbortOnDropHandle<PolarsResult<()>>>,
   |

error[E0433]: failed to resolve: could not find `AbortOnDropHandle` in `task`
   --> /home/sun/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-stream-0.51.0/src/nodes/io_sinks/csv.rs:119:47
    |
119 |         self.io_task = Some(tokio_util::task::AbortOnDropHandle::new(io_task));
    |                                               ^^^^^^^^^^^^^^^^^ could not find `AbortOnDropHandle` in `task`
    |
help: consider importing one of these structs
    |
1   + use crate::nodes::io_sinks::AbortOnDropHandle;
    |
1   + use crate::utils::task_handles_ext::AbortOnDropHandle;
    |
help: if you import `AbortOnDropHandle`, refer to it directly
    |
119 -         self.io_task = Some(tokio_util::task::AbortOnDropHandle::new(io_task));
119 +         self.io_task = Some(AbortOnDropHandle::new(io_task));
    |

error[E0412]: cannot find type `AbortOnDropHandle` in module `tokio_util::task`
  --> /home/sun/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-stream-0.51.0/src/nodes/io_sinks/json.rs:28:39
   |
28 |     io_task: Option<tokio_util::task::AbortOnDropHandle<PolarsResult<()>>>,
   |                                       ^^^^^^^^^^^^^^^^^ not found in `tokio_util::task`
   |
help: consider importing one of these structs
   |
1  + use crate::nodes::io_sinks::AbortOnDropHandle;
   |
1  + use crate::utils::task_handles_ext::AbortOnDropHandle;
   |
help: if you import `AbortOnDropHandle`, refer to it directly
   |
28 -     io_task: Option<tokio_util::task::AbortOnDropHandle<PolarsResult<()>>>,
28 +     io_task: Option<AbortOnDropHandle<PolarsResult<()>>>,
   |

error[E0433]: failed to resolve: could not find `AbortOnDropHandle` in `task`
  --> /home/sun/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-stream-0.51.0/src/nodes/io_sinks/json.rs:89:47
   |
89 |         self.io_task = Some(tokio_util::task::AbortOnDropHandle::new(io_task));
   |                                               ^^^^^^^^^^^^^^^^^ could not find `AbortOnDropHandle` in `task`
   |
help: consider importing one of these structs
   |
1  + use crate::nodes::io_sinks::AbortOnDropHandle;
   |
1  + use crate::utils::task_handles_ext::AbortOnDropHandle;
   |
help: if you import `AbortOnDropHandle`, refer to it directly
   |
89 -         self.io_task = Some(tokio_util::task::AbortOnDropHandle::new(io_task));
89 +         self.io_task = Some(AbortOnDropHandle::new(io_task));
   |

Some errors have detailed explanations: E0412, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `polars-stream` (lib) due to 4 previous errors
```

### Issue description

upgrade to latest rust polars , compile error

### Expected behavior

New release should work on Linux

### Installed versions

<details>
[dependencies]
polars = { version = "0.51", features = ["abs", "diff", "json", "is_in","round_series", "strings", "regex", "lazy", "ewma","rolling_window", "pct_change","timezones","dtype-categorical","dtype-i128"] }
</details>

**Comment by dsprenkels** [comment]
I am presuming that your build setup depends on (some older version of) `tokio-utils` in some place, and Cargo dedups that package.  We should add a constraint to polars to make sure we depend on a version that contains the `AbortOnDropHandle` feature.

**Comment by weixingsun** [comment]
@dsprenkels  Thanks for your comments, I made a workaround by adding an extra line:
tokio-util = "0.7.16"

and it's moving to a new error :

```
   Compiling polars-stream v0.51.0
error[E0599]: no method named `abs` found for struct `polars_plan::plans::AExprBuilder` in the current scope
    --> /Users/sun/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-stream-0.51.0/src/physical_plan/lower_expr.rs:1173:45
     |
1173 |                     let offset_abs = offset.abs(ctx.expr_arena);
     |                                             ^^^ method not found in `polars_plan::plans::AExprBuilder`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `polars-stream` (lib) due to 1 previous error
```

**Comment by dsprenkels** [comment]
@weixingsun Can you try resolving this by enable the polars `abs` feature?

**Comment by weixingsun** [comment]
yeah the new version looks good with abs feature, appreciate so much!
