### ISSUE TITLE
pyo3_polars: no `PyDataFrame` in the root

### ISSUE THREAD

**Issue by graiffgarcia** [pola-rs/polars#23937]
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

A minimally reproducible example:
```rust
use pyo3::prelude::*;
use pyo3_polars::PyDataFrame;


/// Formats the sum of two numbers as string.
#[pyfunction]
fn do_nothing(df: PyDataFrame) -> PyResult<String> {
    Ok("Hello!".to_string())
}

#[pymodule]
#[pyo3(name = "my_module")]
fn my_module(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_function(wrap_pyfunction!(do_nothing, m)?)?;
    Ok(())
}
```

maturin/cargo produces the error:
```
error[E0432]: unresolved import `pyo3_polars::PyDataFrame`
 --> src\lib.rs:2:5
  |
2 | use pyo3_polars::PyDataFrame;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `PyDataFrame` in the root

For more information about this error, try `rustc --explain E0432`.
```

### Log output

```shell

```

### Issue description

The import does not work with pyo3-polars 0.23 in the same way as it used to, but I see no documentation that would point me in the direction of a fix?

### Expected behavior

The expected behavior would be for the PyDataFrame struct to be available for import.

### Installed versions

<details>

rustc 1.88.0, Cargo.toml has `edition = "2021"`

Cargo.toml dependencies:

```toml
[dependencies]
polars = { version = "0.50"}
pyo3-polars = { version = "0.23", features = ["derive"] }
pyo3 = { version = "0.25", features = ["extension-module"] }
```

</details>

**Comment by orlp** [comment]
Should already be fixed with https://github.com/pola-rs/polars/pull/23918?

**Comment by MonkeyChap** [comment]
Having exactly the same problem.

**Comment by orlp** [comment]
This is fixed on the latest release of pyo3-polars.
