### PR TITLE
chore: Bump version of tokio-util due to usage of AbortOnDropHandle

### LINKED ISSUE #24600: Linux compile error on tag 0.51
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

rust 1.88 on Linux 6.1
when upgrading rust polars from 0.50 to 0.51 , recompile app failed 

```rust
/home/test/.cargo/bin/rustc --version
rustc 1.88.0 (6b00bc388 2025-06-23)

```

### Log output

```shell
/home/test/.cargo/bin/cargo build --release
...
compile Compiling polars-stream v0.51.0
error[E0412]: cannot find type `AbortOnDropHandle` in module `tokio_util::task`
  --> /home/sun/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-stream-0.51.0/src/nodes/io_sinks/csv.rs:33:39
   |
33 |     io_task: Option<tokio_util::task::AbortOnDropHandle<PolarsResult<()>>>,
   |                                       ^^^^^^^^^^^^^^^^^ not found in `tokio_util::task`
   |
help: consider importing one of these structs
   |
1  + use crate::nodes::io_sinks::AbortOnDropHandle;
   |
1  + use crate::utils::task_handles_ext::AbortOnDropHandle;
   |
help: if you import `AbortOnDropHandle`, refer to it directly
   |
33 -     io_task: Option<tokio_util::task::AbortOnDropHandle<PolarsResult<()>>>,
33 +     io_task: Option<AbortOnDropHandle<PolarsResult<()>>>,
   |

error[E0433]: failed to resolve: could not find `AbortOnDropHandle` in `task`
   --> /home/sun/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-stream-0.51.0/src/nodes/io_sinks/csv.rs:119:47
    |
119 |         self.io_task = Some(tokio_util::task::AbortOnDropHandle::new(io_task));
    |                                               ^^^^^^^^^^^^^^^^^ could not find `AbortOnDropHandle` in `task`
    |
help: consider importing one of these structs
    |
1   + use crate::nodes::io_sinks::AbortOnDropHandle;
    |
1   + use crate::utils::task_handles_ext::AbortOnDropHandle;
    |
help: if you import `AbortOnDropHandle`, refer to it directly
    |
119 -         self.io_task = Some(tokio_util::task::AbortOnDropHandle::new(io_task));
119 +         self.io_task = Some(AbortOnDropHandle::new(io_task));
    |

error[E0412]: cannot find type `AbortOnDropHandle` in module `tokio_util::task`
  --> /home/sun/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-stream-0.51.0/src/nodes/io_sinks/json.rs:28:39
   |
28 |     io_task: Option<tokio_util::task::AbortOnDropHandle<PolarsResult<()>>>,
   |                                       ^^^^^^^^^^^^^^^^^ not found in `tokio_util::task`
   |
help: consider importing one of these structs
   |
1  + use crate::nodes::io_sinks::AbortOnDropHandle;
   |
1  + use crate::utils::task_handles_ext::AbortOnDropHandle;
   |
help: if you import `AbortOnDropHandle`, refer to it directly
   |
28 -     io_task: Option<tokio_util::task::AbortOnDropHandle<PolarsResult<()>>>,
28 +     io_task: Option<AbortOnDropHandle<PolarsResult<()>>>,
   |

error[E0433]: failed to resolve: could not find `AbortOnDropHandle` in `task`
  --> /home/sun/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-stream-0.51.0/src/nodes/io_sinks/json.rs:89:47
   |
89 |         self.io_task = Some(tokio_util::task::AbortOnDropHandle::new(io_task));
   |                                               ^^^^^^^^^^^^^^^^^ could not find `AbortOnDropHandle` in `task`
   |
help: consider importing one of these structs
   |
1  + use crate::nodes::io_sinks::AbortOnDropHandle;
   |
1  + use crate::utils::task_handles_ext::AbortOnDropHandle;
   |
help: if you import `AbortOnDropHandle`, refer to it directly
   |
89 -         self.io_task = Some(tokio_util::task::AbortOnDropHandle::new(io_task));
89 +         self.io_task = Some(AbortOnDropHandle::new(io_task));
   |

Some errors have detailed explanations: E0412, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `polars-stream` (lib) due to 4 previous errors
```

### Issue description

upgrade to latest rust polars , compile error

### Expected behavior

New release should work on Linux

### Installed versions

<details>
[dependencies]
polars = { version = "0.51", features = ["abs", "diff", "json", "is_in","round_series", "strings", "regex", "lazy", "ewma","rolling_window", "pct_change","timezones","dtype-categorical","dtype-i128"] }
</details>

### PR DESCRIPTION
**Pull request by dsprenkels**
Polars uses the relatively new `tokio-utils` feature `AbortOnDropHandle`. This patch updates the version constraint to require a modern version of the `tokio-utils` crate.

Fixes #24600

### CODE REVIEW

File: Cargo.toml [hunk 1]
```diff
@@ -95,7 +95,7 @@ strength_reduce = "0.2"
 strum = "0.27"
 strum_macros = "0.27"
 tokio = { version = "1.44", default-features = false }
-tokio-util = "0.7.8"
+tokio-util = ">=0.7.13, <0.8.0"
```
Comment (orlp) [inline Cargo.toml]: You can just write this as `"0.7.13"`.

**Review by orlp — CHANGES_REQUESTED** [review]

File: Cargo.toml (hunk 1 above)
Comment (dsprenkels) [reply Cargo.toml]: Oh, I didn't know. Thanks!

Comment (dsprenkels) [reply Cargo.toml]: Wait. Do I not need to also include a tilde? https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements

**Review by nameexhaustion — CHANGES_REQUESTED** [review]
I don't think we need to be taking a dependency on tokio-utils at all. We already have an `AbortOnDropHandle` at https://github.com/pola-rs/polars/blob/main/crates/polars-stream/src/utils/task_handles_ext.rs. We should probably just use that instead

File: Cargo.toml (hunk 1 above)
Comment (orlp) [reply Cargo.toml]: No you don't, caret (the default) already does what we want here.

**Comment by dsprenkels** [comment]
However, `tokio_utils` `AbortOnDropHandle` is also used in `polars-io` which is below `polars-stream` in the dependency tree (where our own `AbortOnDropHandle` is defined).

We could split this off into `polars-utils`, but I think bumping the dependency would be an adequate solution for now.

**Comment by nameexhaustion** [comment]
> However, `tokio_utils` `AbortOnDropHandle` is also used in `polars-io` which is below `polars-stream` in the dependency tree (where our own `AbortOnDropHandle` is defined).

Could you show where in `polars-io` it's used?

**Comment by orlp** [comment]
@dsprenkels I made a PR to just remove this dependency instead.
