### ISSUE TITLE
polars can not be built for wasm from v0.29

### ISSUE THREAD

**Issue by Dirreke** [pola-rs/polars#8783]
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Issue description

V0.29 can not be built for wasm.
It has two problem
1. `POOL` has no method `current_thread_index()` for wasm, which is introduced in #8618 at [hashing.rs](https://github.com/pola-rs/polars/blob/551cd92e1392ba96e737a3785398e83bcecc0633/polars/polars-core/src/frame/groupby/hashing.rs#L30)

2. crate `home` which used in polars-io to replace crate `dir` can not be built for wasm.  #8449 

### Reproducible example

1. `POOL` has no method `current_thread_index()` for wasm, which is introduced in # 8618 at [hashing.rs](https://github.com/pola-rs/polars/blob/551cd92e1392ba96e737a3785398e83bcecc0633/polars/polars-core/src/frame/groupby/hashing.rs#L30)
```
error[E0599]: no method named `current_thread_index` found for struct `once_cell::sync::Lazy<Pool>` in the current scope
  --> ...\polars-core-0.29.0\src\frame\groupby\hashing.rs:30:13
   |
30 |     if POOL.current_thread_index().is_none() {
   |             ^^^^^^^^^^^^^^^^^^^^ method not found in `Lazy<Pool>`
```

for wasm, it has a similar method `current_num_threads()` (I'm not sure if they have the same functionality ) at [`wasm.rs`](https://github.com/pola-rs/polars/blob/551cd92e1392ba96e737a3785398e83bcecc0633/polars/polars-utils/src/wasm.rs#L4-L6). Perhaps it will help

2. crate `home` which used in polars-io to replace crate `dir` can not be built for wasm.  #8449 

```
error[E0425]: cannot find function `home_dir_inner` in the crate root
  --> ...\home-0.5.5\src\env.rs:33:16
   |
33 |         crate::home_dir_inner()
   |                ^^^^^^^^^^^^^^ not found in the crate root
```

### Installed versions

<details>
v0.29
</details>

**Comment by Dirreke** [comment]
0.30 can compile pass

**Comment by lorepozo** [comment]
@Dirreke this is still broken with the same compile errors reported in the original post.

repro:
```sh
$ cargo new bug8783
$ cd bug8783
$ echo 'polars = "0.30"' >> Cargo.toml
$ cargo build --target wasm32-unknown-unknown
```

Similarly with `default-features = false` it fails to compile with the same errors.

Regressions like this are preventable with better coverage, we should be able to build the wasm target from the workflow in `.github/workflows/test-rust.yml`

May I suggest keeping this issue open until CI tests have been added for the WASM target and are passing?

**Comment by Dirreke** [comment]
you are right, I did the wrong test. Actually, it still broke

**Comment by mingsterism** [comment]
hi guys. want to ask has this issue been solved? because we have been trying it out and it still causes bugs. just wanted to know if latest polars can use WASM

**Comment by Dirreke** [comment]
yeah,it has been solved in 0.33

**Comment by kAif-gh** [comment]
i think it's still broken, i have just created an issue in wasm_bindgen issues that describe an encountered problem.[https://github.com/rustwasm/wasm-bindgen/issues/3661](url)
