### ISSUE TITLE
Can't compile with feature=['lazy'] on 0.34.2

### ISSUE THREAD

**Issue by rollo-b2c2** [pola-rs/polars#12050]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```rust

fn main() {

}

```

```toml

[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.34.2", features = ["lazy"]}

```

### Log output

```shell
error[E0432]: unresolved import `polars_plan::dsl::all_horizontal`
  --> /Users/rollokonig-brock/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-lazy-0.34.2/src/frame/mod.rs:28:5
   |
28 | use polars_plan::dsl::all_horizontal;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `all_horizontal` in `dsl`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `polars-lazy` (lib) due to 2 previous errors
```
```


### Issue description

Can't build polars with lazyframe on 0.34.2.

### Expected behavior

For this to build

### Installed versions

lazy

**Comment by ritchie46** [comment]
What is you rust version? As I had that problem as well, but it disappeared when I upgraded. 

In any case, can you make a PR with the proposed change?

**Comment by TuonyBT** [comment]
I also had the problem until I upgraded to rust 1.73

**Comment by flokli** [comment]
https://github.com/pola-rs/polars/issues/12112 seems to track updating MSRV to 1.73, but this might be a compiler bug.

**Comment by lashomb** [comment]
Ran into this one as well with polars 0.34.2 and rust 1.72. After updating to 1.73, it wasn't a problem.

**Comment by stinodego** [comment]
This should be resolved.
