### PR TITLE
chore: Bump Rust dependencies

### LINKED ISSUE #27863: Does not compile with rustc 1.98.0-nightly
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

When adding `polars-core` as a (dev) dependency, the compilation fails with
```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> /home/trch/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ethnum-1.5.2/src/error.rs:16:14
   |
16 |     unsafe { mem::transmute(()) }
   |              ^^^^^^^^^^^^^^
   |
   = note: source type: `()` (0 bits)
   = note: target type: `TryFromIntError` (8 bits)

For more information about this error, try `rustc --explain E0512`.
error: could not compile `ethnum` (lib) due to 1 previous error
```

### Log output

```shell

```

### Issue description

See above.

### Expected behavior

The compilation should succeed. ;-)

### Installed versions

<details>

polars-core = { version = "0.54.3", features = ["fmt"] }

</details>

### PR DESCRIPTION
**Pull request by orlp**
Fixes https://github.com/pola-rs/polars/issues/27863.

Not updated is `sqlparser`, I'd like @alexander-beedie to do that since it added new fields.

### CODE REVIEW

**Comment by alexander-beedie** [comment]
Will do 👍  

FYI: the new `sqlparser` version has a new [`derive_dialect`](https://docs.rs/sqlparser/latest/sqlparser/macro.derive_dialect.html) macro I added that's going to be beneficial for us, though I'll take advantage of that _after_ updating the dependency.
