### ISSUE TITLE
Polars Rust crate does not declare a Minimum Supported Rust Version but cannot compile with anything less than 1.88

### ISSUE THREAD

**Issue by bmitc** [pola-rs/polars#24792]
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

```console
> cargo add polars
<use Polars somewhere in project>

> cargo +1.87 build
error[E0658]: `let` expressions in this position are unstable
   --> /Users/<user>/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-utils-0.51.0/src/plpath.rs:306:12
    |
306 |         if let Some(scheme) = self.scheme()
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

   Compiling bson v2.15.0
For more information about this error, try `rustc --explain E0658`.
error: could not compile `polars-utils` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

> cargo +1.88 build
<succeeds>
```

### Log output

```shell

```

### Issue description

The [Polars crate](https://crates.io/crates/polars) does not declare a Minimum Supported Rust Version (MSRV):

<img width="600" alt="Image" src="https://github.com/user-attachments/assets/02f50f21-2fc2-47b4-96ed-a0f9804d65ff" />

----

However, projects with Polars cannot be built with any Rust version less than `1.88`. This is because, at a minimum, Polars uses `if`-`let` chaining, [which was stabilized in `1.88`](https://blog.rust-lang.org/2025/06/26/Rust-1.88.0/). Here is the use reported by `cargo`:

https://github.com/pola-rs/polars/blob/faab1f8eeeb1ad1a60fbd6e433bfbc3239737422/crates/polars-utils/src/plpath.rs#L346-L356

### Expected behavior

1. Polars should explicitly set a Minimum Supported Rust Version (MSRV) so that `cargo` tooling can know about it.
    * This issue was very unexpected, and luckily I am able to upgrade from `1.85.1` to `1.89`. However, it isn't always possible in our corporate environment to upgrade out of sync with other Rust projects.
3. If the only thing preventing Polars from supporting earlier versions is `if`-`let` chains, then in my opinion, their use should be removed. The above code is very minimally improved by using an `if`-`let` chain.

### Installed versions

<details>

```toml
polars = { version = "0.51.0", optional = true, features = [
    "json",
    "lazy",
    "serde",
    "timezones",
] }
```

</details>

**Comment by ritchie46** [comment]
We don't want to make an effort to support a rust version as minimal as possible, and regularly update the rust compiler. 

If we don't do already, we should communicate that we expect the latest available compiler or the compile in our `toolchain.toml`.

**Comment by orlp** [comment]
You can't specify that your policy is "latest stable Rust only" in a way that crates.io picks up, other than specifying the latest version yourself and manually updating it every time a new stable compiler comes out.

Either way, this is certainly not a bug.

**Comment by bmitc** [comment]
> We don't want to make an effort to support a rust version as minimal as possible, and regularly update the rust compiler.

Is this standard practice in the Rust community? I do see nightly is specified in the repo's `rust-toolchain.toml`. In the given example, is the use of an `if`-`let` chain enough to justify bumping the minimum version?

https://github.com/pola-rs/polars/blob/5b90db75911c70010d0c0a6941046e6144af88d4/rust-toolchain.toml#L2

Even though I've been championing the use of Polars within my (large) company, it means that I am going to have to strip Polars out of our Rust codebases as we aren't able to handle the situation of a dependency constantly upping the minimal version it supports to stable. I recently went through an effort with our corporate licensing team to get Polars approved since there were several licensing issues with Polars, that have now been fixed, but we cannot handle Polars updating its minimum version to stable on every release. In our corporate environment, we update our Rust version every six months or so.

At the minimum, Polars should at least communicate what the minimum supported version is. By not communicating it, users have to constantly figure it out by surprise and trial and error, as I did here.

> this is certainly not a bug

What is it, for future information? I had to choose something from the list, and I didn't select documentation because it is deeper than that.

**Comment by orlp** [comment]
> Is this standard practice in the Rust community? 

I wouldn't say so, but most libraries are rather small whereas Polars is several hundred thousand lines of code. The burden of maintaining a MSRV (and then refactoring code to use the newer features whenever you do bump it) is rather large for us, with little gain.

> In the given example, is the use of an if-let chain enough to justify bumping the minimum version?

We simply like to use the latest features the language offers us, without having to consider every time whether our MSRV supports it.

> it means that I am going to have to strip Polars out of our Rust codebases as we aren't able to handle the situation of a dependency constantly upping the minimal version it supports to stable

You could also pin your Polars version until you are able to update the compiler, and update them in lockstep.

> What is it, for future information? I had to choose something from the list

A (missing) enhancement.

**Comment by eitsupi** [comment]
> Even though I've been championing the use of Polars within my (large) company, it means that I am going to have to strip Polars out of our Rust codebases as we aren't able to handle the situation of a dependency constantly upping the minimal version it supports to stable.

This may be a silly question, but why would you use Rust Polars for something like that when it's not even version 1.0.0?

In my opinion, it seems more reasonable to choose an alternative that is popular in the Rust community, such as DataFusion.

**Comment by bmitc** [comment]
This isn't necessarily an issue for us anymore, at least currently, because we've made the decision to not use Polars in Rust, and I have stripped it out. But a few follow ups.

> whereas Polars is several hundred thousand lines of code. The burden of maintaining a MSRV (and then refactoring code to use the newer features whenever you do bump it) is rather large for us, with little gain.

I actually view it as the opposite. Constantly chasing newer features seems like more of a burden in a large codebase, which normally require more discipline than smaller codebases. Refactoring isn't needed when bumping an MSRV unless a feature is deprecated or new lintings are added.

> without having to consider every time whether our MSRV supports it.

This is solved by setting an MSRV because the compiler and `rust-analyzer` will warn you about this just like anything else in the language. It's not a difficult problem. And in this case, it appears it's just a single `if`-`let` chain.

> This may be a silly question, but why would you use Rust Polars for something like that when it's not even version 1.0.0?

I am confused by this question. You are essentially asking why would anyone use Polars at this point.

**Comment by artob** [comment]
To note, the issue subject could be updated as Rust 1.88 definitely won't suffice, and neither did 1.93. Sorted after upgrading to Rust 1.96 using `rustup update`.

<details>
<summary>Expand the compiler output</summary>

```console
$ cargo --version
cargo 1.93.0 (083ac5135 2025-12-15)
$ cargo run
...
   Compiling polars-config v0.54.4
   Compiling polars-utils v0.54.4
   Compiling polars-schema v0.54.4
   Compiling polars-buffer v0.54.4
   Compiling polars-async v0.54.4
   Compiling polars-arrow v0.54.4
   Compiling polars-compute v0.54.4
   Compiling polars-dtype v0.54.4
   Compiling polars-row v0.54.4
   Compiling polars-parquet v0.54.4
   Compiling polars-core v0.54.4
   Compiling polars-ops v0.54.4
   Compiling polars-io v0.54.4
   Compiling polars-ooc v0.54.4
error[E0658]: use of unstable library feature `cold_path`
   --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-ooc-0.54.4/src/lib.rs:179:9
    |
179 |         std::hint::cold_path();
    |         ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #136873 <https://github.com/rust-lang/rust/issues/136873> for more information

error[E0658]: use of unstable library feature `cold_path`
   --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-ooc-0.54.4/src/lib.rs:213:9
    |
213 |         std::hint::cold_path();
    |         ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #136873 <https://github.com/rust-lang/rust/issues/136873> for more information

error[E0658]: use of unstable library feature `atomic_try_update`
   --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-ooc-0.54.4/src/lib.rs:110:14
    |
110 |             .try_update(Ordering::Acquire, Ordering::Relaxed, |state| {
    |              ^^^^^^^^^^
    |
    = note: see issue #135894 <https://github.com/rust-lang/rust/issues/135894> for more information

error[E0658]: use of unstable library feature `atomic_try_update`
   --> ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/polars-ooc-0.54.4/src/lib.rs:322:14
    |
322 |             .try_update(Ordering::Relaxed, Ordering::Acquire, |state| {
    |              ^^^^^^^^^^
    |
    = note: see issue #135894 <https://github.com/rust-lang/rust/issues/135894> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `polars-ooc` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
</details>

**Comment by bmitc** [comment]
I probably should just close this issue. The maintainers communicated that they don't want to specify a minimal version other than latest (even though there is a minimal version that might not be the latest), so it isn't clear that there's a need for an open issue.
