### PR TITLE
fix(python): fix import error when writing parquet with pyarrow

### LINKED ISSUE #9753: write_parquet(use_pyarrow=True) throws AttributeError
### Polars version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Issue description

After upgrading from 0.17.x to 0.18, I've started getting the following exception when trying to `write_parquet` with `use_pyarrow=True`.

```python
  File "/opt/webapp/parquet.py", line 97, in polars_write_to_parquet
    save_df_to_s3(_writer, _output_path)
  File "/opt/webapp/parquet.py", line 36, in save_df_to_s3
    df_writer(local_path)
  File "/opt/webapp/parquet.py", line 71, in _writer
    _df.write_parquet(
  File "/usr/local/lib/python3.11/site-packages/polars/dataframe/frame.py", line 3101, in write_parquet
    pa.parquet.write_table(
    ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/polars/dependencies.py", line 83, in __getattr__
    return getattr(module, attr)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyarrow/__init__.py", line 335, in __getattr__
    raise AttributeError(
AttributeError: module 'pyarrow' has no attribute 'parquet'
```

### Reproducible example

```python
import polars as pl

    def writer(df, path):
        df.write_parquet(
            path,
            compression="zstd",
            statistics=True,
            use_pyarrow=True, # <====== WORKS IF I COMMENT THIS LINE OUT.
            pyarrow_options={"coerce_timestamps": "us"},
        )
```

### Expected behavior

Was working fine on polars version 0.17.x.  Seems to be a regression against pyarrow.

### Installed versions

<details>

```
--------Version info---------
Polars:              0.18.6
Index type:          UInt32
Platform:            Linux-5.15.49-linuxkit-pr-aarch64-with-glibc2.36
Python:              3.11.4 (main, Jun 14 2023, 18:34:05) [GCC 12.2.0]

----Optional dependencies----
adbc_driver_sqlite:  <not installed>
connectorx:          <not installed>
deltalake:           <not installed>
fsspec:              2023.6.0
matplotlib:          <not installed>
numpy:               1.25.0
pandas:              2.0.3
pyarrow:             11.0.0
pydantic:            <not installed>
sqlalchemy:          <not installed>
xlsx2csv:            <not installed>
xlsxwriter:          <not installed>

```

</details>

### PR DESCRIPTION
**Pull request by MarcoGorelli**
closes #9753

### CODE REVIEW

File: py-polars/tests/unit/io/test_parquet.py [hunk 1]
```diff
@@ -7,7 +7,6 @@
 import pandas as pd
 import pyarrow as pa
 import pyarrow.dataset as ds
-import pyarrow.parquet as pq
```
Comment (MarcoGorelli) [inline py-polars/tests/unit/io/test_parquet.py:10]: moving this inside the test that uses it, so that the new test fails on `main` (so hopefully this issue won't come up again)

File: py-polars/polars/dataframe/frame.py [hunk 2]
```diff
@@ -3095,8 +3095,9 @@ def write_parquet(
 
             tbl = pa.table(data)
 
-            # do not remove this
+            # do not remove this import!
             # needed below
+            import pyarrow.parquet  # noqa: F401
```
Comment (MarcoGorelli) [inline py-polars/polars/dataframe/frame.py:3100]: looks like this was accidentally removed in https://github.com/pola-rs/polars/pull/9592/files 😄
