### ISSUE TITLE
`write_csv` to object storage (s3) broke (Regression 1.30.0)

### ISSUE THREAD

**Issue by Julian-J-S** [pola-rs/polars#22873]
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/polars/) of Polars.

### Reproducible example

```python
  storage_options = {
      "aws_access_key_id": "...",
      "aws_secret_access_key": "...",
      "aws_region": "...",
  }

  df.write_csv(
      file="...",
      include_header=True,
      storage_options=storage_options,
  )
```

### Log output

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 marketing.write_csv_to_marketing_s3(
      2     df=df,
      3     bucket_name=BUCKET_NAME,
      4     file_path=FILE_PATH,
      5     env="prod",
      6 )

File ~/work/databricks/dgdab/src/dgdab/marketing.py:89, in write_csv_to_marketing_s3(df, bucket_name, file_path, env)
     82 storage_options = {
     83     "aws_access_key_id": s3_config.access_key_id,
     84     "aws_secret_access_key": s3_config.secret_access_key,
     85     "aws_region": s3_config.region_name,
     86 }
     88 # Write data to S3 in CSV format
---> 89 polars_df.write_csv(
     90     file=destination,
     91     include_header=True,
     92     separator=",",
     93     storage_options=storage_options,
     94 )
     96 logger.info("Data written successfully.")

File ~/work/databricks/dgdab/.venv/lib/python3.12/site-packages/polars/dataframe/frame.py:2986, in DataFrame.write_csv(self, file, include_bom, include_header, separator, line_terminator, quote_char, batch_size, datetime_format, date_format, time_format, float_scientific, float_precision, null_value, quote_style, storage_options, credential_provider, retries)
   2982 engine: EngineType = "in-memory"
   2984 from polars.lazyframe.opt_flags import QueryOptFlags
-> 2986 self.lazy().sink_csv(
   2987     target,
   2988     include_bom=include_bom,
   2989     include_header=include_header,
   2990     separator=separator,
   2991     line_terminator=line_terminator,
   2992     quote_char=quote_char,
   2993     batch_size=batch_size,
   2994     datetime_format=datetime_format,
   2995     date_format=date_format,
   2996     time_format=time_format,
   2997     float_scientific=float_scientific,
   2998     float_precision=float_precision,
   2999     null_value=null_value,
   3000     quote_style=quote_style,
   3001     storage_options=storage_options,
   3002     credential_provider=credential_provider,
   3003     retries=retries,
   3004     optimizations=QueryOptFlags._eager(),
   3005     engine=engine,
   3006 )
   3008 if should_return_buffer:
   3009     return str(target.getvalue(), encoding="utf-8")  # type: ignore[union-attr]

File ~/work/databricks/dgdab/.venv/lib/python3.12/site-packages/polars/lazyframe/frame.py:3226, in LazyFrame.sink_csv(self, path, include_bom, include_header, separator, line_terminator, quote_char, batch_size, datetime_format, date_format, time_format, float_scientific, float_precision, null_value, quote_style, maintain_order, storage_options, credential_provider, retries, sync_on_close, mkdir, lazy, engine, optimizations)
   3220 engine = _select_engine(engine)
   3222 from polars.io.cloud.credential_provider._builder import (
   3223     _init_credential_provider_builder,
   3224 )
-> 3226 credential_provider_builder = _init_credential_provider_builder(
   3227     credential_provider, path, storage_options, "sink_csv"
   3228 )
   3229 del credential_provider
   3231 if storage_options:

File ~/work/databricks/dgdab/.venv/lib/python3.12/site-packages/polars/io/cloud/credential_provider/_builder.py:371, in _init_credential_provider_builder(credential_provider, source, storage_options, caller_name)
    367         return CredentialProviderBuilder(AutoInit(CredentialProviderGCP))
    369     return None
--> 371 credential_provider_init = f()
    373 if verbose():
    374     eprint(f"_init_credential_provider_builder(): {credential_provider_init = !r}")

File ~/work/databricks/dgdab/.venv/lib/python3.12/site-packages/polars/io/cloud/credential_provider/_builder.py:286, in _init_credential_provider_builder.<locals>.f()
    283 has_endpoint_url = False
    285 if storage_options is not None:
--> 286     for k, v in storage_options.items():
    287         k = k.lower()
    289         # https://docs.rs/object_store/latest/object_store/aws/enum.AmazonS3ConfigKey.html

AttributeError: 'list' object has no attribute 'items'
```

### Issue description

Living on the edge my pipeline used the latest polars 1.30.0 tonight an writing csv to s3 bucket broke.

It worked on 1.29.

Error message is
`AttributeError: 'list' object has no attribute 'items'`

Looks like somewhere in polars `storage_options` is converted to a list???

### Expected behavior

code should work as before

### Installed versions

<details>

```
1.30.0
```

</details>

**Comment by abdolrezat** [comment]
can confirm. [There is ](https://github.com/pola-rs/polars/blob/ee0903b7d8cf4ddfa2a2f342d9ab44dea6e67399/py-polars/polars/dataframe/frame.py#L2977) a conversion to list, introduced in [this commit](https://github.com/pola-rs/polars/commit/bcfa7ec9d99d373642726ca9d90bffec3fee4d5f#diff-50f8a5e1ee71cadef61bbae257a72d6b4549020e76abe947b4ee36ef79d553c6R2956).
