### ISSUE TITLE
`polars-arrow` now requires Rust 1.70

### ISSUE THREAD

**Issue by lukesneeringer** [pola-rs/polars#10509]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://crates.io/crates/polars) of Polars.

### Reproducible example

As of 0.32.1, `polars-arrow` will not compile on Rust >= 1.62, < 1.70, because it uses `Option::is_some_and`, which was stabilized in 1.70.

```sh
cargo build
```

Output:

```
error[E0658]: use of unstable library feature 'is_some_and'
   --> /home/sherpa/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-arrow-0.32.1/src/kernels/rolling/no_nulls/min_max.rs:171:29
    |
171 |                 if entering.is_some_and(|em| $new_is_m(&self.m, em.1) || empty_overlap) {
    |                             ^^^^^^^^^^^
...
203 | minmax_window!(MinWindow, get_min_and_idx, new_is_min, n_sorted_past_min);
    | ------------------------------------------------------------------------- in this macro invocation
    |
    = note: see issue #93050 <https://github.com/rust-lang/rust/issues/93050> for more information
    = note: this error originates in the macro `minmax_window` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: use of unstable library feature 'is_some_and'
   --> /home/sherpa/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-arrow-0.32.1/src/kernels/rolling/no_nulls/min_max.rs:171:29
    |
171 |                 if entering.is_some_and(|em| $new_is_m(&self.m, em.1) || empty_overlap) {
    |                             ^^^^^^^^^^^
...
204 | minmax_window!(MaxWindow, get_max_and_idx, new_is_max, n_sorted_past_max);
    | ------------------------------------------------------------------------- in this macro invocation
    |
    = note: see issue #93050 <https://github.com/rust-lang/rust/issues/93050> for more information
    = note: this error originates in the macro `minmax_window` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Issue description

As of 0.32.1, `polars-arrow` will not compile on Rust >= 1.62, < 1.70, because it uses `Option::is_some_and`, which was stabilized in 1.70.

### Expected behavior

Either it should compile on Rust >= 1.62 as the docs claim, or the docs should be updated to 1.70.

### Installed versions

Rust 1.69

**Comment by trueb2** [comment]
Can we add a CI job to build with MSRV before releasing the crate? I understand that the CI build time of building and testing on nightly and stable for each PR would be aggressive. I just notice that this is the third issue in the last 2 months.
